version: '3'

services:
  kiwe-database:
    container_name: kiwe_local
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "kiwe"
      MYSQL_PASSWORD: "kiwe"
      MYSQL_DATABASE: "kiwe"
    ports:
      - "3309:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"

  kiwe-application:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./config:/srv/code
    ports:
      - "7000:8000"
    depends_on:
      - kiwe-databaste