# Generated by Django 3.2.6 on 2021-09-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('restaurant', models.BooleanField()),
                ('school', models.BooleanField()),
                ('cafe', models.BooleanField()),
                ('party', models.BooleanField()),
                ('some', models.BooleanField()),
                ('lover', models.BooleanField()),
                ('friend', models.BooleanField()),
                ('family', models.BooleanField()),
                ('ten', models.BooleanField()),
                ('twenty', models.BooleanField()),
                ('thirty', models.BooleanField()),
                ('forty', models.BooleanField()),
                ('fifty', models.BooleanField()),
                ('sixty', models.BooleanField()),
            ],
        ),
    ]
