# Generated by Django 3.2.6 on 2021-09-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiword', '0002_answer_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='answer',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice1',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='family',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='fifty',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='forty',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='lover',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='party',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='school',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='sixty',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='some',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='thirty',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='twenty',
        ),
    ]
