# Generated by Django 3.2.6 on 2021-09-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiword', '0003_auto_20210909_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiword.choice')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiword.keyword')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiword.question')),
            ],
        ),
    ]
