# Generated by Django 3.2.6 on 2021-09-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiword', '0004_keywordrelated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordrelated',
            name='choice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='keywordrelated',
            name='question',
            field=models.IntegerField(),
        ),
    ]
