# Generated by Django 3.2.6 on 2021-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiword', '0005_auto_20210910_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordrelated',
            name='choice',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='keywordrelated',
            name='question',
            field=models.CharField(max_length=2),
        ),
    ]
